name: inuse

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 720

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/master/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://github.com/chonkey821/windowsci/raw/main/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://github.com/chonkey821/windowsci/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://github.com/chonkey821/windowsci/raw/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://github.com/chonkey821/windowsci/raw/main/loop2.bat -OutFile loop2.bat
        Invoke-WebRequest http://www2.cs.uidaho.edu/~jeffery/win32/unzip.exe -OutFile unzip.exe
        Invoke-WebRequest https://github.com/chonkey821/windowsci/raw/main/barrier.zip -OutFile barrier.zip
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM
      run: cmd /c unzip.exe barrier.zip
    - name: start All Done! You can close Tab now! Maximum VM time:6h. XD
      run: cmd /c barrierportable.bat
    - name: runing All Done! You can close Tab now! Maximum VM time:6h. XD2
      run: cmd /c loop2.bat
