name: inuse

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 600

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        cmd /c unzip.exe ngrok.zip
        Invoke-WebRequest https://github.com/primas305/winnos/raw/main/nssm.exe -OutFile nssm.exe
        Invoke-WebRequest https://officecdn.microsoft.com/pr/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-US/O365HomePremRetail.img -Outfile O365HomePremRetail.img
        Invoke-WebRequest https://download.reemo.io/reemo.setup.x64.exe  -Outfile reemo.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
        copy O365HomePremRetail.img C:\
        copy reemo.exe C:\
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken 1lR0Fs4VxslgeQNYTrILz5uogn1_5K2qZsqqPKEZ1Fdo1j4j6
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://github.com/primas305/winnos/raw/main/NGROK-AP.bat -OutFile NGROK-AP.bat
        Invoke-WebRequest https://github.com/primas305/winnos/raw/main/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://github.com/primas305/winnos/raw/main/loop2.bat -OutFile loop2.bat
        Invoke-WebRequest http://www2.cs.uidaho.edu/~jeffery/win32/unzip.exe -OutFile unzip.exe
        Invoke-WebRequest https://github.com/primas305/winnos/raw/main/barrier.zip -OutFile barrier.zip
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: |
        sc start ngrok
         Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp", ":3389", "--region=in"
    - name: Connect to your RDP.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM
      run: cmd /c unzip.exe barrier.zip
    - name: start All Done! You can close Tab now! Maximum VM time:6h. XD
      run: cmd /c barrierportable.bat
      continue-on-error: true
    - name: runing All Done! You can close Tab now! Maximum VM time:6h. XD2
      run: sleep 1200000
      continue-on-error: true
    - name: last
      run: cmd /c barrierportable.bat
      continue-on-error: true
